"use client";
import './globals.css'
import type { Metadata } from 'next'

import AOS from "aos";
import 'aos/dist/aos.css';
import Lenis from "@studio-freight/lenis";
import { useEffect } from "react";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    const lenis = new Lenis();
    lenis.on("scroll", (e: any) => { });

    function raf(time: any) {
      lenis.raf(time);
      requestAnimationFrame(raf);
    }
    requestAnimationFrame(raf);
  }, []);
  useEffect(() => {
    AOS.init({});
  }, []);
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  )
}
